# Generated by Django 2.0.3 on 2018-03-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20180322_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
