# Generated by Django 2.0.3 on 2018-03-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
