# Generated by Django 2.0.3 on 2018-03-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20180322_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendment',
            name='end_position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amendment',
            name='pending',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amendment',
            name='start_position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
