# Generated by Django 2.0.3 on 2018-03-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20180322_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendment',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
