# Generated by Django 2.0.3 on 2018-03-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20180322_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='uploaded_by',
            field=models.CharField(default='Megan', max_length=200),
            preserve_default=False,
        ),
    ]
