# Generated by Django 2.0.3 on 2018-04-06 17:26

import contracts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_version_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendment',
            name='risk_value',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='version',
            name='file',
            field=models.FileField(upload_to=contracts.models.version_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])]),
        ),
    ]
