# Generated by Django 2.0.3 on 2018-03-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateStorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='description',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='original_file',
            field=models.FileField(upload_to='repository/'),
        ),
    ]
