# Generated by Django 2.0.3 on 2018-03-18 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateStorage', '0002_auto_20180318_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttemplate',
            name='publisher_name',
        ),
    ]
