# Generated by Django 2.0.3 on 2018-03-18 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('templateStorage', '0003_remove_contracttemplate_publisher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttemplate',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
